# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := DigitalWriteFastDemo
ARDUINO_LIBS := EpoxyMockDigitalWriteFast
include ../../../../EpoxyDuino.mk
