# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := DirectoryTest
ARDUINO_LIBS := AUnit UnixHostFS
include $(HOME)/src/UnixHostDuino/UnixHostDuino.mk
