# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloUnixHostFS
ARDUINO_LIBS := UnixHostFS
include ../../../UnixHostDuino/UnixHostDuino.mk
