# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := IPAddressTest
ARDUINO_LIBS := AUnit AceCommon
EPOXY_CORE := EPOXY_CORE_ESP8266
include ../../EpoxyDuino.mk
