# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := StdioSerialWrite
ARDUINO_LIBS :=
include ../../../EpoxyDuino/EpoxyDuino.mk
