# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := EpoxyPromAvrTest
ARDUINO_LIBS := EpoxyPromAvr AUnit
MORE_CLEAN := more_clean
include ../../../../EpoxyDuino.mk

more_clean:
	rm -f epoxypromdata
