# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloUnixHostFS
#ARDUINO_LIB_DIR := $(HOME)/src/arduino/libraries
ARDUINO_LIBS := UnixHostFS
include $(HOME)/src/UnixHostDuino/UnixHostDuino.mk
